# week1 : Basic linear algebra exercises in python

Name : Swetha.K
Roll No : 235229143    

# Exercise : 1

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [3]:
c=np.dot(a,b)

In [5]:
print("matrix c=a*b:")
print(c)

matrix c=a*b:
[[19 22]
 [43 50]]


In [4]:
print("matrix a:")
print(a)
print("matrix b:")
print(b)

matrix a:
[[1 2]
 [3 4]]
matrix b:
[[5 6]
 [7 8]]


# Exercise : 2

In [6]:
import numpy as np

In [7]:
a=np.array([[4,2],[1,3]])

In [8]:
eigenvalues,eigenvectors=np.linalg.eig(a)

In [9]:
print("matrix a:")
print(a)

matrix a:
[[4 2]
 [1 3]]


In [13]:
print("Eigen values:")
print(eigenvalues)

Eigen values:
[5. 2.]


In [14]:
print("Eigen vectors:")
print(eigenvectors)

Eigen vectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


# Exercise : 3

In [16]:
import numpy as np

In [17]:
a=np.array([[3,2,2],[2,3,-2]])

In [18]:
u,s,v=np.linalg.svd(a)

In [19]:
print("matrix a:")
print(a)

matrix a:
[[ 3  2  2]
 [ 2  3 -2]]


In [20]:
print("u matrix:")
print(u)

u matrix:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [21]:
print("singular value:")
print(s)

singular value:
[5. 3.]


In [22]:
print("v matrix:")
print(v)

v matrix:
[[-7.07106781e-01 -7.07106781e-01 -5.55111512e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


# Exercise : 4

In [23]:
import numpy as np

In [24]:
a=np.array([[6,1],[2,3]])

In [25]:
det=np.linalg.det(a)

In [26]:
print("matrix a:")
print(a)

matrix a:
[[6 1]
 [2 3]]


In [27]:
print("Determinant of a:")
print(det)

Determinant of a:
15.999999999999998


# Exercise : 5

In [28]:
import numpy as np 

In [29]:
v=np.array([3,4])

In [30]:
l1_norm=np.linalg.norm(v,ord=1)

In [31]:
l2_norm=np.linalg.norm(v)

In [32]:
print("matrix v:")
print(v)

matrix v:
[3 4]


In [33]:
print("l1 norm of v:")
print(l1_norm)

l1 norm of v:
7.0


In [34]:
print("l2 norm of v:")
print(l2_norm)

l2 norm of v:
5.0
